import { createFileRoute } from "@tanstack/react-router";

import poster from "../assets/story-cinema.jpg";
import { useStore } from "../components/storefront";
export const Route = createFileRoute("/about")({ staticData: { sitemap: true }, head: () => ({ meta: [{ title: "Our Story — Smooth Tiger" }, { name: "description", content: "The childhood tea ritual behind the name Smooth Tiger." }, { property: "og:title", content: "Our Story — Smooth Tiger" }, { property: "og:description", content: "The childhood tea ritual behind the name Smooth Tiger." }, { property: "og:type", content: "article" }, { name: "twitter:card", content: "summary_large_image" }, { property: "og:url", content: "/about" }], links: [{ rel: "canonical", href: "/about" }] }), component: AboutPage });
const storyText = { tr: ["Dört yaşında bir çocuk, televizyonun karşısında, gözleri hayranlıkla açılmış, bir WWE gösterisini izliyor.", "Ekrandaki her harekete kendi sesleriyle eşlik ediyor; bang, slam, gosh!", "Annesi, çay doldururken onu açık plan mutfaktan izliyor. Yüzündeki gülümseme gösteriden yükselen gürültü hakkındaki düşünceleri ile pek de örtüşmüyor!", "Anne, çocuğa ılımış bir kupa çay uzatıyor. Çocuk çayı büyük bir keyifle, neredeyse tek yudumda içiyor.", "Gösteri sona eriyor. Çocuk kendi kendine mırıldanıyor: “John Cena… Hardcore Holly… Edge…”", "Anne söze giriyor: “Peki, sen bir WWE güreşçisi olsaydın, adın ne olurdu?”", "Çocuk annesinin gözlerinin içine bakıyor. Sesli düşünürken “Smooth” der. “Smooth Tiger.”"], en: ["A four-year-old boy watches a WWE show on TV with awe on his face.", "He makes sounds to accompany the action; bang, slam, gosh!", "His mother watches the boy from an open-plan kitchen whilst pouring tea, a smile on her face contradicting her thoughts about the noise coming from the loud show!", "She gives the boy a mug of lukewarm tea and watches him gulping it down in ecstasy.", "The show ends as the boy murmurs, “John Cena”, “Hardcore Holly”, “Edge”…", "The mother interrupts and asks, “What would your name be if you were a WWE wrestler?”", "The boy looks her in the eye, thinking aloud, and says; “Smooth.” “Smooth Tiger.”"] };
function AboutPage(){ const { locale }=useStore(); const tr=locale==="tr"; return <main className="about-page">
  <section className="about-hero story-film"><video preload="metadata" poster={poster} autoPlay muted loop playsInline aria-label={tr?"Hikâyemizin filmi":"Film of our story"}><source src="/media/story.webm" type="video/webm"/><source src="/media/story.mp4" type="video/mp4"/></video><div className="story-film-title"><small>{tr?"Hakkımızda · Kısa film":"About · Short film"}</small><h1>{tr?"Hikâyemiz":"Our Story"}</h1><p>{tr?"Bir oturma odası, ılımış bir çay ve bir isim.":"A living room, a lukewarm tea and a name."}</p></div></section>
  <section className="story-onomato story-onomato-row" aria-hidden="true"><b>Bang.</b><b>Slam.</b><b>Gosh!</b></section>
  <section className="story-split"><aside className="story-aside"><img src={poster} alt={tr?"Turkuaz ışıkta çay dolduran anne ve maç izleyen çocuk — Smooth Tiger hikâyesi":"A mother pouring tea in turquoise light while a boy watches wrestling — the Smooth Tiger story"} loading="lazy" /><p>{tr?"Bir çocuk, bir kupa çay ve bir isim — Smooth Tiger böyle doğdu.":"A boy, a mug of tea and a name — this is how Smooth Tiger was born."}</p></aside><div className="story-grid">{storyText[locale].map((p,i)=><article className={i===6?"story-card is-final":"story-card"} key={i}><span>{String(i+1).padStart(2,"0")}</span><p>{p}</p></article>)}</div></section>
  <section className="final-word"><span>Smooth.</span><strong>Smooth Tiger.</strong></section></main>}
